name: softhebb
channels:
  - pytorch
  - fastchan
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=eigen
  - absl-py=0.13.0=pyhd8ed1ab_0
  - adversarial-robustness-toolbox=1.7.1=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py38h497a2fe_0
  - aiohttp-cors=0.7.0=py_0
  - aioredis=1.3.1=py_0
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bayesian-optimization=1.1.0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - blessings=1.7=py38h578d9bd_1004
  - blinker=1.4=py_1
  - boto3=1.20.24=pyhd3eb1b0_0
  - botocore=1.23.24=pyhd3eb1b0_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2022.3.29=h06a4308_1
  - cachetools=4.2.2=pyhd8ed1ab_0
  - catalogue=2.0.6=py38h578d9bd_0
  - certifi=2021.10.8=py38h578d9bd_2
  - cffi=1.14.6=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py38h578d9bd_0
  - cma=3.0.3=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorful=0.5.4=pyhd8ed1ab_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - curl=7.78.0=h1ccaba5_0
  - cycler=0.10.0=py38_0
  - cymem=2.0.5=py38h2531618_0
  - cython-blis=0.7.4=py38h27cfd23_1
  - dataclasses=0.8=pyhc8e2a94_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py38h709712a_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - eagerpy=0.29.0=pyh9f0ad1d_0
  - einops=0.3.2=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h2531618_2
  - fastdownload=0.0.5=py_0
  - ffmpeg=4.3=hf484d3e_0
  - ffmpeg-python=0.2.0=py_0
  - filelock=3.0.12=pyh9f0ad1d_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - foolbox=3.3.1=pyh44b312d_1
  - freetype=2.10.4=h5ab3b9f_0
  - fsspec=2021.10.1=pyhd8ed1ab_0
  - future=0.18.2=py38h578d9bd_3
  - gast=0.3.3=py_0
  - gettext=0.19.8.1=h0b5b191_1005
  - git=2.32.0=pl5262hc120c5b_1
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - glib=2.69.0=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-api-core=1.31.1=pyhd8ed1ab_0
  - google-auth=1.34.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-cloud-core=1.7.1=pyhd3eb1b0_0
  - google-cloud-storage=1.31.0=py_0
  - google-crc32c=1.1.2=py38h27cfd23_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - google-resumable-media=1.3.1=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py38h578d9bd_0
  - gpustat=0.6.0=pyhd8ed1ab_1
  - grpcio=1.38.1=py38hdd6454d_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=2.10.0=nompi_py38h9915d05_106
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - hiredis=1.1.0=py38h1e0a361_1
  - icu=58.2=he6710b0_3
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.6.3=py38h578d9bd_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=6.4.1=py38he5a9106_0
  - ipython=7.28.0=py38he5a9106_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=7.0.3=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py38h2531618_0
  - kornia=0.5.8=pyhd8ed1ab_0
  - krb5=1.19.2=hcc1bbae_0
  - lame=3.100=h7b6447c_0
  - langcodes=3.3.0=pyhd8ed1ab_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=11_linux64_mkl
  - libcblas=3.9.0=11_linux64_mkl
  - libcrc32c=1.1.1=he6710b0_2
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=11_linux64_mkl
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.43.0=h812cca2_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h780b84a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - llvmlite=0.36.0=py38h4630a5e_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib=3.4.2=py38h06a4308_0
  - matplotlib-base=3.4.2=py38hab158f2_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1004
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - msgpack-python=1.0.2=py38h1fd1430_1
  - multidict=5.1.0=py38h497a2fe_1
  - munkres=1.1.4=py_0
  - murmurhash=1.0.5=py38h2531618_0
  - mypy=0.910=py38h497a2fe_0
  - mypy_extensions=0.4.3=py38h578d9bd_3
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.2.0=py38h578d9bd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - notebook=6.4.4=pyha770c72_0
  - numba=0.53.1=py38h8b71fd7_1
  - numpy=1.20.3=py38hf144106_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - nvidia-ml=7.352.0=py_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=py_0
  - opencensus=0.7.13=pyhd8ed1ab_0
  - opencensus-context=0.1.2=py38h578d9bd_4
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1n=h7f8727e_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.1=py38h1abd341_0
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pathy=0.6.0=pyhd3eb1b0_0
  - patsy=0.5.1=py_0
  - pcre=8.45=h295c915_0
  - pcre2=10.35=h14c3975_1
  - perl=5.32.1=0_h7f98852_perl5
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py38h2c7a002_0
  - pip=21.2.2=py38h06a4308_0
  - preshed=3.0.5=py38h2531618_4
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - protobuf=3.17.2=py38h709712a_0
  - psutil=5.8.0=py38h497a2fe_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydantic=1.8.2=py38h497a2fe_0
  - pydeprecate=0.3.1=pyhd8ed1ab_0
  - pydub=0.25.1=pyhd8ed1ab_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pynndescent=0.5.6=pyh6c4a22f_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.7.1=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pytorch-lightning=1.4.9=pyhd8ed1ab_0
  - pytorch-model-summary=0.1.1=py_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_0
  - pyzmq=19.0.2=py38ha71036d_2
  - qt=5.9.7=h5867ecd_1
  - ray-core=1.4.0=py38h9ba0119_1
  - ray-tune=1.4.0=py38h578d9bd_1
  - readline=8.1=h27cfd23_0
  - redis-py=3.5.3=pyh9f0ad1d_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - resampy=0.2.2=py_0
  - rsa=4.7.2=pyh44b312d_0
  - s3transfer=0.5.0=pyhd3eb1b0_0
  - scikit-learn=0.22.1=py38hcdab131_1
  - scipy=1.4.1=py38h18bccfc_3
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setproctitle=1.1.10=py38h497a2fe_1004
  - setuptools=52.0.0=py38h06a4308_0
  - shellingham=1.3.1=pyhd3eb1b0_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyhd3eb1b0_0
  - smart_open=5.1.0=pyhd3eb1b0_0
  - smmap=3.0.5=pyh44b312d_0
  - spacy=3.2.1=py38hae6d005_0
  - spacy-legacy=3.0.8=pyhd8ed1ab_0
  - spacy-loggers=1.0.1=pyhd8ed1ab_0
  - sqlite=3.36.0=hc218d9a_0
  - srsly=2.4.1=py38h2531618_0
  - statsmodels=0.12.2=py38h5c078b8_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tbb=2020.2=h4bd325d_4
  - tensorboard=2.6.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py38h2b97feb_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorboardx=2.4=pyhd8ed1ab_0
  - tensorflow=2.3.0=eigen_py38h71ff20e_0
  - tensorflow-base=2.3.0=eigen_py38hb57a387_0
  - tensorflow-estimator=2.5.0=pyh81a9013_1
  - termcolor=1.1.0=py_2
  - terminado=0.12.1=py38h578d9bd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - thinc=8.0.13=py38hae6d005_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=0.7.2=py38
  - torchmetrics=0.5.1=pyhd8ed1ab_0
  - torchvision=0.8.2=py38_cu101
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.62.0=pyhd8ed1ab_0
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typer=0.4.0=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - umap-learn=0.5.3=py38h578d9bd_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wasabi=0.8.2=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - wrapt=1.12.1=py38h497a2fe_3
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h497a2fe_2
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - --trusted-host pypi.org
    - --trusted-host pypi.python.org
    - --trusted-host files.pythonhosted.org
    - --trusted-host download.pytorch.org
    - efficientnet-pytorch==0.7.1
    - kmeans-pytorch==0.3
    - torchsummary==1.5.1
prefix: /home/username/anaconda3/envs/softhebb # if this path cannot be found, it will be installed under anaconda dir
